### ISSUE TITLE
Ability to link related datasets

### ISSUE THREAD

**Issue by MeganLaurance** [CDLUC3/dash#13]
This enhancement request comes from a group of UCSF researchers who were given a DataShare demo and presentation.  They will publish 4-5 papers from the data funded by a large multi-center NIH grant.  They are likely to upload 4-5 different datasets separately, but would like to be able to link them together somehow, as they are all related to the same project.  

This is an enhancement request to enable users to link related datasets within Dash (DataShare).

**Comment by strasser** [comment]
This is now possible with the "links" field in Dash 1.1
