### ISSUE TITLE
Add DataCite metadata fields for geo metadata

### ISSUE THREAD

**Issue by ghost** [CDLUC3/dash#21]
DataCite metadata fields geoLocationPoint, geoLocationBox, geoLocationPlace, relatedIdentifier, relatedIdentifierType and relationType available as optional metadata fields to enter via GUI & display on data record page

Needed for UCI Data Portal & OC Data Portal project. Feasibility confirmed via 1/23/14 email conversation w/ Stephen Abrams.

**Comment by cpwillett** [comment]
This is now in production for UC Irvine.
