### ISSUE TITLE
can't add a new Contributor or Keyword to an existing record without uploading a new file

### ISSUE THREAD

**Issue by MeganLaurance** [CDLUC3/dash#27]
This bug was brought to my attention by a UCSF researcher who recently deposited a dataset.  Here is the use case:

The user submitted a dataset and record on 7/14/14:  "The dataset "Tobacco-free retailers project" was successfully uploaded at 2014-07-14T12:36:19-07:00.  The identifier associated with this dataset is wliveytggi; doi:10.7272/Q6X63JT1."    She then realized that she should have added another author and keyword, and went back into the record on 7/15/14, the next day, to edit the metadata.  She added two new Keywords and 1 new Creator.  Her additions were visible, but she was unable to click the "Send to DataShare" button.  It was greyed out.  The only way she could get the "Send to DataShare" button to become active was to upload an empty text file and then Send to DataShare.

The expected behavior for the user would be that they could update the metadata and Send to DataShare without having to upload any other files.

We reproduced this bug in her environment (she was using Chrome), and mine (Firefox).  

Oddly enough - I remember being able to add a new keyword to one of my records recently, doi:10.7272/q6td9v7j, without any issues.  Maybe this happened because her record was still "in transit" and hadn't made the round trip back to DataShare?

**Comment by marisastrong** [comment]
this has been resolved.  For initial submission, you must submit a dataset with a file.  After this initial submission, you may make edits to the metadata and submit the updates without having to add another dataset/file.
