### ISSUE TITLE
Help Text for Rights / Rights URI on metadata submission

### ISSUE THREAD

**Issue by ghost** [CDLUC3/dash#34]
The help text for the Rights / Rights URI fields in metadata submission interface is currently undefined. Tested on dash.lib.uci.edu and dash-dev.lib.uci.edu

This will likely be a field researchers have questions about, so some short explanation for CDL's decision to assign a CC-by 4.0 would be useful.

**Comment by strasser** [comment]
Good catch @matthewmckinley ! We've created an internal ticket to fix this. https://www.pivotaltracker.com/story/show/80055262

**Comment by cpwillett** [comment]
Help text is available now.
