### ISSUE TITLE
"Data manager" field confusing on review page

### ISSUE THREAD

**Issue by strasser** [CDLUC3/dash#64]
Currently the data submitter is labeled as the "data manager". This should say "submitter" instead - that way it's clear that the field is auto-populated with the name of the person who's logged in.

![dash__data_submission](https://cloud.githubusercontent.com/assets/418026/5459929/82010cd8-8513-11e4-8cf4-2568483e5884.jpg)

**Comment by cpwillett** [comment]
Now says "Contributor"
