### ISSUE TITLE
add field for grant information

### ISSUE THREAD

**Issue by MeganLaurance** [CDLUC3/dash#7]
This enhancement request was brought up by some potential users at UCSF.  When I presented DataShare to them they said that they have to site their NIH grant when depositing data into a public repository.  They were wondering where they would put that info in DataShare.  The enhancement request is to add a field for citing the grant that funded the data being deposited.

**Comment by pcruse** [comment]
Good one Megan.  I could also see adding http://www.crossref.org/fundref/

**Comment by pcruse** [comment]
Good one Megan -- I could also see adding http://www.crossref.org/fundref/

**Comment by strasser** [comment]
T - you closed the issue, by accident I assume. Can you try re-opening it?

~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
Carly Strasser http://www.carlystrasser.net

**Comment by MeganLaurance** [comment]
Trying to find it again…

**Comment by pcruse** [comment]
Argh… it doesn’t look like I can reopen it.  Should I just add it again?

t

**Comment by strasser** [comment]
I added it again

~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
Carly Strasser http://www.carlystrasser.net/
