### ISSUE TITLE
Type value listed twice on data record page?

### ISSUE THREAD

**Issue by ghost** [CDLUC3/dash#72]
On each data record page, the 'Type' value is always listed twice. For example, 'Dataset: Dataset' or 'Image: Image'.

Not sure if this is a bug... if not, our team wondered what the reasoning was behind this double listing.

**Comment by cpwillett** [comment]
There are two values in the metadata:
&lt;resourceType resourceTypeGeneral="Dataset"&gt;Dataset&lt;/resourceType&gt;

The attribute value is from a restricted list. The element value is free text, but we just duplicate the attribute value here. So there's no point in showing both in the UI.

**Comment by cpwillett** [comment]
Fixed and deployed to dev, stage and production
