### ISSUE TITLE
Requesting addition to OC Data Portal 'about' text

### ISSUE THREAD

**Issue by ghost** [CDLUC3/dash#76]
Please add the following text to the first section of the OC Data Portal About page:

https://dash.lib.uci.edu/xtf/search?smode=about-orangecounty

CURRENT: The Orange County Data Portal features data collected in or pertaining to Orange County, California. All data added to the Orange County Data Portal will also appear in the main UCI Dash interface.
ADDING:  The data portal is inspired by UCI’s Ecological Data Portal which documented data collected in and around Orange County.  This content is now incorporated into the OC Data Portal.

**Comment by cpwillett** [comment]
Change is in production.
