### ISSUE TITLE
Cannot recover from exceeding 10 GB limit

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dash#82]
If you create an object that exceeds the 10 GB limit, you cannot just delete files to get under the limit. You have to start over.

**Comment by cpwillett** [comment]
If you delete files to get under the 10 GB limit, and then go to the My Datasets page, and "edit" the dataset, you can proceed. Maybe we just need to say this in the popup window.

**Comment by marisastrong** [comment]
https://www.pivotaltracker.com/story/show/111076208

after receiving message of going over max limit, I deleted files and proceeded to the submit/review page to verify fix. Closing issue.
