### ISSUE TITLE
Campus logo missing from /logout_page 

### ISSUE THREAD

**Issue by cpwillett** [CDLUC3/dash#83]
I'm not sure what's possible here, since I think this page is static. From a campus page, eg:
![uci_screen_shot](https://cloud.githubusercontent.com/assets/1558172/12122455/04840308-b390-11e5-8045-d37ef71f14e6.png)

if you logout, (and go to /logout_page), the campus logo disappears:
![logout_page](https://cloud.githubusercontent.com/assets/1558172/12122470/19427cca-b390-11e5-96dd-1d2e002cb609.png)

**Comment by marisastrong** [comment]
https://www.pivotaltracker.com/story/show/111077430
