### ISSUE TITLE
Add field for grant information

### ISSUE THREAD

**Issue by strasser** [CDLUC3/dash#9]
This enhancement request was brought up by some potential users at UCSF. When I presented DataShare to them they said that they have to site their NIH grant when depositing data into a public repository. They were wondering where they would put that info in DataShare. The enhancement request is to add a field for citing the grant that funded the data being deposited.

**Comment by strasser** [comment]
Re-adding @MeganLaurance issue since @pcruse accidentally closed it...

**Comment by cpwillett** [comment]
Could be included in Datacite metadata as contributor, with contributorType=funder. fundRef identifier would go as nameIdentifier attribute in contributorName. Eg.,
&lt;contributors&gt;
&lt;contributor contributorType="funder"&gt;
&lt;contributorName nameIdentifier="10.13039/100000001" nameIdentifierScheme="FundRef"&gt;National Science Foundation&lt;/contributorName&gt;
&lt;/contributor&gt;
&lt;/contributors&gt;

**Comment by strasser** [comment]
This was implemented in the most recent version of Dash (1.1)
